---
apiVersion: v1
kind: Namespace
metadata:
  name: webscale-firmware
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-fwupdate
  namespace: webscale-firmware
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-firmware-update
  namespace: webscale-firmware
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: serviceaccount-fwupdate
  namespace: webscale-firmware
---
apiVersion: v1
kind: Pod
metadata:
  name: firmware
  namespace: webscale-firmware
spec:
  serviceAccountName: serviceaccount-fwupdate
  hostNetwork: true
  hostPID: true
  hostIPC: true
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  containers:
    - name: firmware
      image:  quay.io/nburr/firmware:latest
      #      command: ["/bin/bash", "-c", "tail -f /dev/null"]
      securityContext:
        runAsUser: 0
        privileged: true
        appArmorProfile: unconfined
        seLinuxOptions:
          type: spc_t
  volumes:
  - name: usb-devices
    hostPath:
      path: /dev/bus/usb
  - name: modules
    hostPath:
      path: /lib/modules
  volumeMounts:
  - name: usb-devices
    mountPath: /dev/bus/usb
    readOnly: false
  - mountPath: /lib/modules
    name: modules
    readOnly: false